test 25

diff --git a/.github/workflows/az_tf_plan.yml b/.github/workflows/az_tf_plan.yml
--- a/.github/workflows/az_tf_plan.yml
+++ b/.github/workflows/az_tf_plan.yml
@@ -78,34 +78,36 @@ jobs:
       - name: check common variables
         run: echo "Common resource group ${{ needs.varss.outputs.az_mgmt_resource_group }}"
 
+      - name: string test
+        run: echo ${{ format('{0}dev.tfvars', $${{ needs.variables.outputs.tf_vars_file }}}}
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2.0.3
-        with:
-          terraform_version: ${{ inputs.tf_version }}
+#       - name: Setup Terraform
+#         uses: hashicorp/setup-terraform@v2.0.3
+#         with:
+#           terraform_version: ${{ inputs.tf_version }}
 
-      - name: Terraform Format
-        id: fmt
-        run: terraform fmt --check
+#       - name: Terraform Format
+#         id: fmt
+#         run: terraform fmt --check
 
-      - name: Terraform Init
-        id: init
-        run: | 
-          terraform init \
-          --backend-config="storage_account_name=$${{ needs.variables.outputs.az_mgmt_storage_acc }}" \
-          --backend-config="container_name=${{ needs.variables.outputs.az_mgmt_container_name }}" \
-          --backend-config="resource_group_name=${{ needs.variables.outputs.az_mgmt_resource_group }}" \
-          --backend-config="key=$${{ needs.variables.outputs.tf_key }}"
+#       - name: Terraform Init
+#         id: init
+#         run: | 
+#           terraform init \
+#           --backend-config="storage_account_name=$${{ needs.variables.outputs.az_mgmt_storage_acc }}" \
+#           --backend-config="container_name=${{ needs.variables.outputs.az_mgmt_container_name }}" \
+#           --backend-config="resource_group_name=${{ needs.variables.outputs.az_mgmt_resource_group }}" \
+#           --backend-config="key=$${{ needs.variables.outputs.tf_key }}"
       
-      - name: Terraform Validate
-        id: validate
-        run: terraform validate
+#       - name: Terraform Validate
+#         id: validate
+#         run: terraform validate
 
-      - name: Terraform Plan
-        id: plan
-        run: terraform plan --var-file=$TF_VARS --out=plan.tfplan
-        continue-on-error: true
+#       - name: Terraform Plan
+#         id: plan
+#         run: terraform plan --var-file="$${{ needs.variables.outputs.tf_vars_file }} --out=plan.tfplan
+#         continue-on-error: true
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+#       - name: Terraform Plan Status
+#         if: steps.plan.outcome == 'failure'
+#         run: exit 1
