test1 again

diff --git a/.github/workflows/az_tf_plan.yml b/.github/workflows/az_tf_plan.yml
--- a/.github/workflows/az_tf_plan.yml
+++ b/.github/workflows/az_tf_plan.yml
@@ -70,36 +70,37 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v3.3.0
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2.0.3
-        with:
-          terraform_version: ${{ inputs.tf_version }}
-
-      - name: Terraform Format
-        id: fmt
-        run: terraform fmt --check
-
-      - name: Terraform Init
-        id: init
-        run: | 
-          terraform init \
-          --backend-config="storage_account_name=$STORAGE_ACCOUNT" \
-          --backend-config="container_name=$CONTAINER_NAME" \
-          --backend-config="resource_group_name=$RESOURCE_GROUP" \
-          --backend-config="key=$TF_KEY"
-      
-      - name: Terraform Validate
-        id: validate
-        run: terraform validate
-
       - name: check string
         run: echo $STORAGE_ACCOUNT
 
-      - name: Terraform Plan
-        id: plan
-        run: terraform plan --var-file=$TF_VARS --out=plan.tfplan
-        continue-on-error: true
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+      # - name: Setup Terraform
+      #   uses: hashicorp/setup-terraform@v2.0.3
+      #   with:
+      #     terraform_version: ${{ inputs.tf_version }}
+
+      # - name: Terraform Format
+      #   id: fmt
+      #   run: terraform fmt --check
+
+      # - name: Terraform Init
+      #   id: init
+      #   run: | 
+      #     terraform init \
+      #     --backend-config="storage_account_name=$STORAGE_ACCOUNT" \
+      #     --backend-config="container_name=$CONTAINER_NAME" \
+      #     --backend-config="resource_group_name=$RESOURCE_GROUP" \
+      #     --backend-config="key=$TF_KEY"
+      
+      # - name: Terraform Validate
+      #   id: validate
+      #   run: terraform validate
+
+      # - name: Terraform Plan
+      #   id: plan
+      #   run: terraform plan --var-file=$TF_VARS --out=plan.tfplan
+      #   continue-on-error: true
+
+      # - name: Terraform Plan Status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
