Update deploy-pull-request.yml

diff --git a/.github/workflows/deploy-pull-request.yml b/.github/workflows/deploy-pull-request.yml
--- a/.github/workflows/deploy-pull-request.yml
+++ b/.github/workflows/deploy-pull-request.yml
@@ -1,12 +1,11 @@
-name: 'Deploy-pull-request'
+name: 'Deploy-all'
 on:
- # Pull will create plan and deploy to a development workspace
-   pull_request:
-     branches: 
-       - main
-   workflow_dispatch:
+  pull_request:
+    branches:
+      - main
+  workflow_dispatch:
   
-jobs:
+jobs:    
   # Get variable files (currently on for all environments)  
   variables: 
     uses: ./.github/workflows/variables.yml
@@ -45,12 +44,15 @@ jobs:
             az storage container create --name ${{ needs.variables.outputs.az_mgmt_container_name }} --account-name "${{ needs.variables.outputs.az_mgmt_storage_acc }}dev"
   
 ########################################################################################################################################
-# Development deployment
+# Development
+
 
  # Build plan
   build-plan:
     runs-on: ubuntu-latest
-    needs: [build_management_dev, variables]
+    needs: build_management_dev
+    permissions:
+      pull-requests: write
     environment: dev
     env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
@@ -88,28 +90,53 @@ jobs:
         run: terraform validate
 
       - name: Terraform Plan
+        if: github.event_name == 'pull_request'
         id: plan
         run: terraform plan --var-file=config_dev.tfvars.json --out=plan.tfplan -input=false
         continue-on-error: true
-
-# Save plan for re-use in build
-      - name: Compress TF Plan artifact
-        run: zip -r ${{ needs.variables.outputs.tf_key }}.zip ./*
-        
-      - name: Upload Artifact
-        uses: actions/upload-artifact@v3.1.2
-        with:
-          name: "${{ needs.variables.outputs.tf_key }}"
-          path: "tf_core/${{ needs.variables.outputs.tf_key }}.zip"
-          retention-days: 5
       
-#       # Artifacts from the Plan
-#       - name: Download Artifact
-#         uses: actions/download-artifact@v3.0.2
-#         with:
-#           name: ${{ needs.variables.outputs.tf_key }}
-#           path: tf_core
+      # adds a comment to the pull request with the results of the format, init and plan steps  
+      - name: Update Pull Request
+        uses: actions/github-script@v6
+        if: github.event_name == 'pull_request'
+        env:
+          PLAN: "${{ steps.plan.outputs.stdout }}"
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
 
-# #  Deploy to devp
+            <details><summary>Show Plan</summary>
+
+            \`\`\`terraform\n
+            ${process.env.PLAN}
+            \`\`\`
+
+            </details>
+
+            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: output
+            })  
+
+      # Returns whether a plan was successfully generated or not. This step highlights whenever a plan fails because the Terraform Plan step continues on error.
+      - name: Terraform Plan Status
+        if: steps.plan.outcome == 'failure'
+        run: exit 1
+
+
+##################### Created on PR upto this point. In dev environment ##################################################################################
+
 #       - name: Terraform Apply
-#         run: terraform apply plan.tfplan
+#         if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+#         run: terraform apply -auto-approve -input=false
+
+########################################################################################################################################
+
